---
- name: Check if node already joined cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join cluster
  ansible.builtin.command: "{{ k8s_join_command }}"
  when: not kubelet_conf.stat.exists
  changed_when: true
