---
- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Reload and enable disable-swap unit
  ansible.builtin.systemd:
    name: disable-swap
    daemon_reload: true
    enabled: true
    state: started
